## numpy vs list speed test

In [1]:
import numpy as np
import time

In [2]:
print("using pyhton list")
size = 1_000_000


l1= list(range(size))
l2 = list(range(size))

start = time.time()
add = [x+y for x,y in zip(l1,l2)]

end = time.time()

print(end-start)

using pyhton list
0.049263954162597656


In [3]:
print("using python numpy arrays")

size = 1_000_000
l1 = np.array(list(range(size)))
l2 = np.array(list(range(size)))

start = time.time()
add = l1+l2

end = time.time()

print(end-start)

using python numpy arrays
0.006790876388549805


In [4]:
print("checkin g the storage consuptaions")
import sys 
list_data = list(range(1000))
numpy_data = np.array(list_data)

print(f"python list size: {sys.getsizeof(list_data)*len(list_data)} bytes")
print(f"python numpy array size: {numpy_data.nbytes} bytes")

checkin g the storage consuptaions
python list size: 8056000 bytes
python numpy array size: 8000 bytes


In [5]:
print("the final time check")

start_1 = time.time()
list_sqr = [x**2 for x in list(range(100))]
end_1 = time.time()

print(f"list time: {end_1 - start_1}")

start_2 = time.time()
numpy_sqr = np.array(list(range(100)))**2
end_2 = time.time()

print(f"numpy time: {end_2 - start_2}")


the final time check
list time: 3.409385681152344e-05
numpy time: 3.5762786865234375e-05


# CREATING NUMPY ARRAYS 

In [6]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([[1,2,3],[4,5,6]])

print(arr1)
print(arr2)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [10]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
np.arange(1,100,9) #1->99 but adding 9 to each element after the first one !!

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [12]:
np.linspace(0,1,5)  #generate equally spaced array

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [16]:
myarr.shape

(4, 3)

In [17]:
myarr.size

12

In [18]:
myarr.ndim

2

In [19]:
myarr.dtype

dtype('int64')

In [20]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype="float32")
myarr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [21]:
myarr.dtype

dtype('float32')

In [22]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
myarr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
myarr.shape

(4, 3)

In [24]:
reshape = myarr.reshape(3,4)

In [25]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [26]:
reshape.reshape(2,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
reshape.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# INDEXING AND SLICING IN A NUMPY ARRAY

In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [3]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
flat = arr.flatten()

In [5]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
flat[0]

1

In [7]:
flat[3]

4

In [8]:
flat[3:6]

array([4, 5, 6])

In [9]:
flat[:5]

array([1, 2, 3, 4, 5])

In [10]:
flat[3:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
flat[::2]  #every second element of the numpy array 

array([ 1,  3,  5,  7,  9, 11])

In [12]:
flat 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
b = flat[3:7]
b

array([4, 5, 6, 7])

In [14]:
b[0] = 444444

In [15]:
b

array([444444,      5,      6,      7])

In [16]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     10,     11,     12])

In [17]:
c = flat[3:7].copy()

In [18]:
c

array([444444,      5,      6,      7])

In [19]:
c[0] = 567

In [21]:
c

array([567,   5,   6,   7])

In [22]:
flat

array([     1,      2,      3, 444444,      5,      6,      7,      8,
            9,     10,     11,     12])

In [23]:
arr2 = np.array([1,54,23,53,2,3,34,5,6])

idx = [1,4,6]

In [24]:
arr2[idx]

array([54,  2, 34])

In [25]:
#boolean masking 

arr2[arr2>3]

array([54, 23, 53, 34,  5,  6])

# EXCERCISE 

In [29]:
# Create a 3×3 array filled with random numbers and print its shape.

arr_3by3 = np.random.randint(0,100,size=(3,3))
print(arr_3by3)
print(arr_3by3.shape)

[[35  1 97]
 [46 17  9]
 [74  4 93]]
(3, 3)


In [30]:
# Convert an array of floats [1.1, 2.2, 3.3] into integers.

arr_floattoint = np.array([1.1,2.2,3.3],dtype="int")
arr_floattoint 

array([1, 2, 3])

In [32]:
# Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
arr_fancy = np.array([1,2,3,4,5,6])
condition = arr_fancy%2==0
arr_fancy[condition]

array([2, 4, 6])

In [33]:
# Reshape a 1D array of size 9 into a 3×3 matrix.

arr_reshape =  np.random.randint(0,50,size=9)
print(arr_reshape)
arr_reshape = arr_reshape.reshape((3,3))
arr_reshape

[44 14 13 47 27 48 29  3 45]


array([[44, 14, 13],
       [47, 27, 48],
       [29,  3, 45]])

In [34]:
# Use boolean masking to filter numbers greater than 50 in an array.
arr_booleanmask = np.random.randint(30,60,size=9)
condn = arr_booleanmask > 50
arr_booleanmask[condn]

array([59, 52, 51, 57])

# MULTIDIMENSIONAL INDEXING AND AXIS

In [1]:
import numpy as np

In [2]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
arr[0]

array([1, 2, 3])

In [4]:
arr[1]

array([4, 5, 6])

In [5]:
# axis =0, responds to column 
# axis = 1, respods to rows

np.sum(arr,axis=0)  # all columns elements sum

array([12, 15, 18])

In [6]:
np.sum(arr,axis=1) # all rows elements sum

array([ 6, 15, 24])

In [8]:
arr[0][1]

2

In [9]:
arr[0,1] #0th row and 1st column

2

In [10]:
arr[0:2, 1:3] #0:2-> returns rows 0 and 1, 1:3 -> return columns 1:2

array([[2, 3],
       [5, 6]])

In [11]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

print(arr3D)
print(arr3D.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [12]:
arr3D[0,1,2]

6

In [13]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

# NUMPY DATA TYPES 

# NUMPY DATATYPES

In [17]:
arr = np.array([23,4,3,23])
arr.dtype

dtype('int64')

In [18]:
arr.astype("float64")

array([23.,  4.,  3., 23.])

In [19]:
arr.dtype

dtype('int64')

In [20]:
arr.nbytes

32

# NUMPY BROADCASTING

In [21]:
arr = np.array([1,2,3,4,5])
result = arr + 10 

In [23]:
result


# [1,2,3,4,5] + [10,10,10,10,10] = [11,12,13,14,15]

array([11, 12, 13, 14, 15])

In [24]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([1, 2, 3])
 
result = arr1 + arr2  # Broadcasting arr2 across arr1
print(result)
# Output:
# [[2 4 6]
#  [5 7 9]]



[[2 4 6]
 [5 7 9]]


# numpy mathematical functions

In [3]:
import numpy as np
arr = np.array([3,5,2,33])

In [4]:
arr

array([ 3,  5,  2, 33])

In [5]:
np.mean(arr)

10.75

In [6]:
np.min(arr)

2

In [7]:
np.max(arr)

33

In [8]:
np.var(arr)

166.1875

In [9]:
np.std(arr)

12.891373084353738

In [10]:
np.sum(arr)

43

In [11]:
np.prod(arr)

990

In [14]:
np.percentile(arr,50)

4.0

In [15]:
np.argmin(arr)

2

In [16]:
np.argmax(arr)

3

In [17]:
np.unique(arr)

array([ 2,  3,  5, 33])

## for more mathematical functions we can check the official documentation or w3school website or gfg website 

In [18]:
print("that's it!!, now moving on to pandas!!")

that's it!!, now moving on to pandas!!
